#!/usr/bin/env python

def describe_pet(animal_type, pet_name):
    '''Display information about a pet.'''
    print('\nI have a ' + animal_type + '.')
    print('My ' + animal_type + 's name is ' + pet_name.title() + '.')

#describe_pet(animal_type='hamster', pet_name='harry')


class Dog(): #Class
    """A simple attempt to model a dog."""

    def __init__(self, name, age): #Method
        """Initialize name and age attributes"""
        self.name = name
        self.age = age

    def sit(self):
        """Simulate a dog sitting in response to a command"""
        print(self.name.title() + " is now sitting.")

    def roll_over(self):
        """Simulate rolling over in response to a command."""
        print(self.name.title() + " rolled over!")

my_dog = Dog("willie", 6)

print("My dog's name is " + my_dog.name.title() + ".")
print("My dog is " + str(my_dog.age) + " years old.")
